### PR TITLE
WIP:Adding Fateforge fonts & fix Nodesto

### PR DESCRIPTION
**Pull request by lucastucious**

### CODE REVIEW

**Comment by lucastucious** [comment]
I have fixed some mistakes made when I edited Nodesto ! How nobody see that 😭

**Comment by jonathonf** [comment]
Could you split this into two PRs, one for Nodesto and one for the Fateforge additions (and squash things down into the minimum number of commits)?

**Comment by graycastle** [comment]
@lucastucious Were the issues with Nodes around the width of the space character? If so, once broken into two PRs per @jonathonf, this might address my reported issue (and likely prevent my inexperienced use of Font Forge from breaking things further 🤣)

**Comment by graycastle** [comment]
@lucastucious Is resolving this to the comment above possible?

**Comment by lucastucious** [comment]
Sorry, i wasn't very active online theses past month !

**Pull request closed without merging**
